config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "places#index"
  resources :places, only: %i[create index new show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/place.rb
class Place < ApplicationRecord
  validates_presence_of :address
  after_validation :call_geocoder

  private

  def call_geocoder
    if self.address.present?
      result = Geocoder.search(self.address).first
      self.latitude = result.latitude
      self.longitude = result.longitude
      self.postal_code = result.postal_code || "#{result.city}::#{result.country_code}"
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/places_controller.rb
class PlacesController < ApplicationController
  def index
    @places = Place.where.not(latitude: nil, longitude: nil)
  end

  def show
    @place = Place.find(params[:id])

    @cached = true
    @dailies = Rails.cache.fetch(@place.postal_code, expires_in: 30.minutes) do
      @cached = false
      Weather::Client.get_forecast(@place.latitude, @place.longitude)
    end

  rescue ActiveRecord::RecordNotFound => e
    flash[:notice] = "No saved place with that ID"
    redirect_to action: :index
  end

  def new
    @place = Place.new
  end

  def create
    @place = Place.new(place_params)

    if @place.save
      redirect_to @place
    else
      render :new, status: :unprocessable_entity
    end
  end

  private

  def place_params
    params.require(:place).permit(:address)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/places_helper.rb
module PlacesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Address Weather Lookup App</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/places/index.html.erb
<h2>Saved Addresses</h2>

<div class="row">
  <%= link_to "Look up weather at a new address", new_place_path %>
</div>

<hr/>

<% @places.each do |place| %>
  <div class="row">
    <div class="col-sm-1">
      <%= place.postal_code %>
    </div>
    <div class="col-sm-2">
      <%= link_to place.address, place %>
    </div>
    <div class="col-sm">
      (<%= place.latitude %>, <%= place.longitude %>)
    </div>
  </div>
<% end %>

app/views/places/new.html.erb
<div class="card">
  <div class="card-body">
    <h5 class="card-title">Get Weather at New Address</h5>

<%= form_with model: @place do |form| %>
  <div class="row">
    <%= form.label "Enter Address" %><br/>
    <%= form.text_field :address %>
    <% @place.errors.full_messages_for(:address).each do |message| %>
      <%= message %>
    <% end %>
  </div>

  <div class="row">
    <%= form.submit "Get Weather" %><br/>
  </div>
<% end %>

app/views/places/show.html.erb
<h2 class="card-title"><%= @place.address %></h2>

<%= link_to "Saved Addresses", places_path %>

<hr />

<div class="row">
  <label class="col-sm-1">Address</label>
  <span class="col-sm-2"><%= @place.address %></span>
</div>
<div class="row">
  <label class="col-sm-1">Latitude</label>
  <span class="col-sm-2"><%= @place.latitude %></span>
</div>
<div class="row">
  <label class="col-sm-1">Longitude</label>
  <span class="col-sm-2"><%= @place.longitude %></span>
</div>
<% if @cached %>
  <div class="col-sm-3 text-success">
    <i class="bi bi-check"></i>
    Cached
  </div>
<% else %>
  <div class="col-sm-3 text-warning">
    <i class="bi bi-radar"></i>
    Retrieved
  </div>
<% end %>

<div class="row">
  <% @dailies.each do |daily| %>
    <div class="card col-sm-3">
      <div class="card-body">
        <h5 class="card-title"><%= daily[:when] %></h5>

        <div class="row">
          <% daily[:temperatures].each_with_index do |temp, i| %>
            <div class="col">
              <%= i == 0 ? "High" : "Low" %>: <%= temp[:value] %>
              <%= image_tag(temp[:icon]) %>
            </div>
          <% end %>
        </div>

      </div>
    </div>
  <% end %>
</div>